# which ports to listen on,
#what files to serve,
#what limits and rules apply,
#and how to handle special routes (uploads, CGI, etc).  

error_log ./logs/error.log;
pid ./catsurf.pid;

server
{
    listen 8080;
    server_name catsurf_example.com www.catsurf_example.com;
    # location {};  
    #error_page
   #  root ;  
}
server
{
    listen 8081;
    server_name cgi.catsurf_example.com www.cgi.catsurf_example.com;
    root www;
    index index.html;
    cgi_timeout 30s;
    cgi_idle_timeout 2s;

    location /cgi {
        root www/cgi-bin/python;
        allow_methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    location /cgi-php {
        root www/cgi-bin/php;
        allow_methods GET POST;
        cgi_extension .php;
        cgi_path /usr/bin/php-cgi;
    }
}
server
{
    listen 8082;
    server_name test.catsurf_example.com www.test.catsurf_example.com;
    # location {};  
    #error_page
    # root;  
}
