# which ports to listen on,
#what files to serve,
#what limits and rules apply,
#and how to handle special routes (uploads, CGI, etc).  

worker_processes 4;
error_log ./logs/error.log;
pid ./catsurf.pid;

server
{
    listen 8080;
    server_name catsurf_example.com www.catsurf_example.com;
    # location {};  
    #error_page
   #  root ;  
}
server
{
    listen 8081;
    server_name cgi.catsurf_example.com www.cgi.catsurf_example.com;
    
    # location {};  
    #error_page
   #  root;  
}
server
{
    listen 8082;
    server_name test.catsurf_example.com www.test.catsurf_example.com;
    # location {};  
    #error_page
    # root;  
}