# Demo configuration for the CatSurf CGI pipeline.

server
{
    listen 8080;
    server_name localhost;
    root www;
    index index.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /cgi-python {
        root www/cgi-bin/python;
        allow_methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        client_max_body_size 1M;
        index echo.py query_params.py;
    }

    location /cgi-php {
        root www/cgi-bin/php;
        allow_methods GET POST;
        cgi_extension .php;
        cgi_path /usr/bin/php-cgi;
        client_max_body_size 2M;
        index upload.php query_params.php;
    }

    location /cgi-sh {
        root www/cgi-bin/sh;
        allow_methods GET;
        cgi_extension .sh;
        cgi_path /bin/sh;
        index date.sh query_params.sh;
    }
}
