error_log /logs/error.log;
pid /logs/catsurf.pid;

server 
{
    listen 127.0.0.1:8080;
    server_name catsurf.com www.catsurf.com;
    root www;
    index index.html index.htm;
    error_page 404 /error_pages/404.html;
    client_max_body_size 4326236499999999999;
    timeout 100;

    location /miao/ {
        index index2.html;
    }

     location /miao {
        index index.html;
    }

    location /stuff {
        root www/images;
        autoindex on;
    }

    location /feed/ {
        root www/feed;
        upload_path uploads;
        index post.html;
    }

    location /idk {
        return 301 /feed;
    }

    location /try {
        root www/tryStuff;
    }

    location /err {
        return 404;
    }

    location /errorcss {
        root www/error_pages;
        index error.css;
    }

    location /cgi-python {
        root www/cgi-bin/python;
        allow_methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        client_max_body_size 1M;
        index echo.py query_params.py;
    }

    location /cgi-php/ {
        root www/cgi-bin/php;
        allow_methods GET POST;
        cgi_extension .php;
        cgi_path /usr/bin/php-cgi;
        client_max_body_size 2M;
        index upload.php query_params.php;
    }

    location /cgi-sh {
        root www/cgi-bin/sh;
        allow_methods GET;
        cgi_extension .sh;
        cgi_path /bin/sh;
        index date.sh query_params.sh;
    }

    location /upload {
        allow_methods POST DELETE;
        upload_path uploads;
    }
}



server 
{
    listen 9110;
    server_name default;
    root www/catshare;
    index index.html index.htm;
    error_page 404 /error_pages/404.html;
    client_max_body_size 4326236499999999999;
    timeout 100;

    location /catpics {
        allow_methods GET POST DELETE;
        root www/catshare/uploads;
        upload_path www/catshare/uploads;
        autoindex on;
    }
    

}

server 
{
    listen 8110;
    server_name default;
    root www/WhatsCat/public;
    index index.html index.htm;
    error_page 404 /error_pages/404.html;
    client_max_body_size 4326236499999999999;
    timeout 100;

    location /cgi-bin {
        root www/WhatsCat/cgi-bin;
        allow_methods GET POST DELETE;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        client_max_body_size 1M;
        index chat.py;
    }

}


server 
{
    listen 7110;
    server_name default;
    root www/catinder;
    index index.html index.htm;
    error_page 404 /error_pages/404.html;
    client_max_body_size 4326236499999999999;
    timeout 100;

    location /getcat {
        root www/cgi-bin/python;
        allow_methods GET;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        client_max_body_size 1M;
        index cat_api.py;
    }

}

server
{
    listen 8081;
    server_name default;
    root www;
    index index.html;
}
