error_log logs/error.log;
pid logs/catsurf.pid;

server 
{
    listen 8080;
    server_name catsurf.com www.catsurf.com;
    root /var/www/html;
    index index.html index.htm;
    error_page 404 /404.html;
    client_max_body_size 10M;
    timeout 100;

    location / {
        root /var/www/html;
        autoindex off;
        allow_methods GET POST;
        upload_path /tmp/uploads;
        cgi_extension .php;
        cgi_path /usr/bin/php-cgi;
        client_max_body_size 20M;
        return 200 /index.html;
    }
    location /sub {
        root /var/www/html/sub;
        upload_path /tmp/uploads;
    }
}

server
{
    listen 8081;
    server_name default;
    root /var/www/default;
    index index.html;
}
