#unclosed server block
error_log /logs/error.log;
pid /logs/catsurf.pid;

server 
{
    listen 127.0.0.1:8080;
    server_name catsurf.com www.catsurf.com;
    root www;
    index index.html index.htm;
    error_page 404 /error_pages/404.html;
    client_max_body_size 22463463460;
    timeout 100;

    location /miao/ {
        index index2.html;
    }

     location /miao {
        index index.html;
    }
