#mssing root
server
{
    listen 8080;
    server_name catsurf_example.com www.catsurf_example.com;
    location {};
    #error_page
    root
}
server
{
    listen 8081;
    server_name cgi.catsurf_example.com www.cgi.catsurf_example.com;
    location {};
    root www;
}
