server {
     listen 8080;
     client_max_body_size 2k;
     location / {
    autoindex off;
    client_max_body_size 20M;
    allow_methods GET POST DELETE;
    }
         location /hello {
    autoindex on;
    allow_methods GET POST;
    cgi_extension .php;
    upload_path /var/www/uploads;
            cgi_path /usr/bin/php-cgi;
    }
}